### ISSUE TITLE
Path works differently than :s3 storage engine.

### ISSUE THREAD

**Issue by pvertenten** [igor-alexandrov/paperclip-aws#3]
Something to note.

We switching from the :s3 storage engine to this, because of various other dependency issues with s3 libraries, and to add the capability to enable server side encryption.

One headache we ran into was with the :s3 storage engine our paths were setup as "/some/path/to/file" this made the key some/path/to/file, the s3 storage engine would remove the leading / from the key used with s3.

The aws storage engine does not have the logic to remove the leading /, so previously uploaded files were not capable of being found anymore, and ay newly uploaded files had a / in the key name.

To ease adoption it might be better to be consistent with how the path gets translated into a key.

**Comment by igor-alexandrov** [comment]
Tried to understand what are you talking about, but cannot.
Can you give some real examples, please?

**Comment by igor-alexandrov** [comment]
Fixed in 1.3.0.
