### ISSUE TITLE
using :private permissions and the paperclip-aws url method

### ISSUE THREAD

**Issue by clayheaton** [igor-alexandrov/paperclip-aws#6]
Maybe this isn't an issue as much as it is a documentation request. I would like to avoid using the :public_read s3 permissions in favor of :private, if possible. 

My understanding from reading the docs is that I just need to use the `:s3_permissions => :private` option and then embed an image with some code that looks something like:

``` erb
<%= image_tag f.object.image.pic.url(:tiny, {:expires => 10}) %>
```

That doesn't work for me, however. What method do you use with this gem to access s3 assets that aren't `:public_read`?

**Comment by igor-alexandrov** [comment]
I think that you should use :authenticated_read level. You can read a bit more about this here in comments: https://github.com/amazonwebservices/aws-sdk-for-ruby/blob/master/lib/aws/s3/s3_object.rb.

Also you should understand, that link generated with such call `f.object.image.pic.url(:tiny, :expires => 10)` will exist only 10 seconds. Maybe you should increase expiration time or create a download method that will redirect users to your uploads.

**Comment by clayheaton** [comment]
You were right... `:authenticated_read` is what I needed. I've been poking around in a lot of other tutorials that suggested `:private` was possible, but it doesn't seem to work for me with my setup. Thanks again!

**Comment by igor-alexandrov** [comment]
:private in S3 means, that only you can read your data.
:authenticated_read – you can grant authorization to other users, this is what you do with expiration_token.
